const path = require('path');
const logDir = path.resolve(__dirname, 'logs');

module.exports = {
  apps: [
    {
      name: 'nodeprism-api',
      cwd: './packages/api',
      script: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 3000,
      out_file: path.join(logDir, 'api-out.log'),
      error_file: path.join(logDir, 'api-error.log'),
      merge_logs: true,
      time: true,
    },
    {
      name: 'nodeprism-web',
      cwd: './packages/web',
      script: 'node_modules/.bin/next',
      args: 'start',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 3000,
      out_file: path.join(logDir, 'web-out.log'),
      error_file: path.join(logDir, 'web-error.log'),
      merge_logs: true,
      time: true,
    },
    {
      name: 'nodeprism-config-sync',
      cwd: './packages/config-sync',
      script: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 5000,
      out_file: path.join(logDir, 'config-sync-out.log'),
      error_file: path.join(logDir, 'config-sync-error.log'),
      merge_logs: true,
      time: true,
    },
    {
      name: 'nodeprism-anomaly-detector',
      cwd: './packages/anomaly-detector',
      script: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 5000,
      out_file: path.join(logDir, 'anomaly-detector-out.log'),
      error_file: path.join(logDir, 'anomaly-detector-error.log'),
      merge_logs: true,
      time: true,
    },
    {
      name: 'nodeprism-agent',
      cwd: './packages/agent-app',
      script: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
        MANAGER_URL: 'http://localhost:4000',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 3000,
      out_file: path.join(logDir, 'agent-out.log'),
      error_file: path.join(logDir, 'agent-error.log'),
      merge_logs: true,
      time: true,
    },
  ],
};
