apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  # Loki
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000

  # PostgreSQL
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: nodeprism
    database: nodeprism
    editable: true
    secureJsonData:
      password: $__env{DB_PASSWORD}
    jsonData:
      database: nodeprism
      sslmode: disable
      postgresVersion: 1500
